openapi: 3.1.0
info:
  title: Road Network Management API
  description: >-
    REST API for managing road networks, uploading, updating and retrieving road
    networks
  version: 1.0.0
paths:
  /users/:
    post:
      tags:
        - users
      summary: Create a new user
      description: Creates a user with the provided details.
      operationId: create_user_users__post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUser'
            example:
              username: my_user
              email: my_user@coldmail.com
              hashed_password: A_sword
              role: USER
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReadUser'
        '201':
          description: User successfully created
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
